<a href="https://colab.research.google.com/github/mrzResearchArena/esm-embedding-clustering/blob/main/Clustering-kmeans-HC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/drive')

Drive already mounted at /drive; to attempt to forcibly remount, call drive.mount("/drive", force_remount=True).


In [2]:
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
# from sklearn.decomposition import PCA
import time

In [ ]:
# # X = np.array([[1, 2],
#               [1, 4],
#               [1, 0],
#               [10, 2],
#               [10, 4],
#               [10, 0]])
# X

In [ ]:
!ls

sample_data


In [ ]:
!pwd

/content


In [ ]:
X = np.load('/drive/My Drive/ESM/Xs-35667.npy')

In [ ]:
X.shape

(35667, 1280)

In [ ]:
# np.save(file='Xcosine.npy', arr=Xcosine)

In [ ]:
# Xcosine = np.load('Xcosine.npy')

In [ ]:
# Xcosine.shape

In [ ]:
# pca = PCA(n_components=1000)

In [ ]:
# begin = time.time()

# pca.fit(Xcosine)

# print(time.time() - begin)

In [ ]:
# begin = time.time()

# kmeans = KMeans(n_clusters=2, random_state=0, verbose=0).fit(X)

# print(time.time() - begin)

In [ ]:
# kmeansOutputs = kmeans.labels_

In [ ]:
# set(kmeansOutputs)

In [ ]:
# np.save(arr=kmeansOutputs, file='kmeans')

In [ ]:
# X = np.load('/drive/My Drive/ESM/Xs-35667.npy')

In [ ]:
# X.shape

(35667, 1280)

In [ ]:
HCmodel = AgglomerativeClustering(n_clusters=536, affinity='cosine', linkage='average')

In [ ]:
begin = time.time()

HCmodel.fit(X)

print(time.time() - begin)

In [ ]:
HCmodel.labels_

In [ ]:
# https://github.com/DeMoriarty/fast_pytorch_kmeans/blob/master/fast_pytorch_kmeans/kmeans.py
# https://github.com/subhadarship/kmeans_pytorch
https://stackoverflow.com/questions/44759982/are-there-any-implementations-of-kmeans-with-cosine-distance-in-apache-spark-pys

### K-Means (PyTorch Acceleration)

- This tool can run on both GPU and CPU.
    - However, I am forced to use CPU memory. Be that as it may, the CPU contains more memory compared to GPU in Google Colab Pro (i.e., The available CPU and GPU memory are 25.5 GB and 14.5 GB, respectively.).

- able to train batch-wise

In [2]:
# !pip install kmeans-pytorch
!pip install git+https://github.com/subhadarship/kmeans_pytorch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/subhadarship/kmeans_pytorch to /tmp/pip-req-build-36_hnh_y
  Running command git clone -q https://github.com/subhadarship/kmeans_pytorch /tmp/pip-req-build-36_hnh_y
  Created wheel for kmeans-pytorch: filename=kmeans_pytorch-0.3-py3-none-any.whl size=10310 sha256=fb03b7a406c6d4439a0c8c7ca3eb28448a4af1d05017d960822e5b40af24dae6
  Stored in directory: /tmp/pip-ephem-wheel-cache-mv_w6uq5/wheels/48/2d/12/6bd529adcb4ffb4f45ed39fa9cef9d69c96100b091bb54286c
Successfully built kmeans-pytorch


In [3]:
import torch
import numpy as np
import matplotlib.pyplot as plt
from kmeans_pytorch import kmeans, kmeans_predict
import time

In [4]:
# set random seed
np.random.seed(101)

In [6]:
from google.colab import drive
drive.mount('/drive')

Mounted at /drive


In [7]:
# data
X = np.load('/drive/My Drive/ESM/Xs-35667.npy')
X.shape

(35667, 1280)

In [8]:
# X = X[:10000,:]
X.shape

(35667, 1280)

In [9]:
X = torch.from_numpy(X)
X.shape

torch.Size([35667, 1280])

In [15]:
# set device
# if torch.cuda.is_available():
#     device = torch.device('cuda:0')
# else:
#     device = torch.device('cpu')

device = torch.device('cpu')
print(f'device: {device}')

device: cpu


In [11]:
help(kmeans)

Help on function kmeans in module kmeans_pytorch:

kmeans(X, num_clusters, distance='euclidean', cluster_centers=[], tol=0.0001, tqdm_flag=True, iter_limit=0, device=device(type='cpu'), gamma_for_soft_dtw=0.001, seed=None)
    perform kmeans
    :param X: (torch.tensor) matrix
    :param num_clusters: (int) number of clusters
    :param distance: (str) distance [options: 'euclidean', 'cosine'] [default: 'euclidean']
    :param seed: (int) seed for kmeans
    :param tol: (float) threshold [default: 0.0001]
    :param device: (torch.device) device [default: cpu]
    :param tqdm_flag: Allows to turn logs on and off
    :param iter_limit: hard limit for max number of iterations
    :param gamma_for_soft_dtw: approaches to (hard) DTW as gamma -> 0
    :return: (torch.tensor, torch.tensor) cluster ids, cluster centers



In [16]:
# k-means

num_clusters = 153

begin = time.time()

cluster_ids_x, cluster_centers = kmeans(
    X=X[:30000,:],
    num_clusters=num_clusters,
    distance='cosine',
    device=device,
)

print()
print(time.time() - begin)

running k-means on cpu..



[running kmeans]: 0it [00:00, ?it/s]
[running kmeans]: 0it [00:08, ?it/s, center_shift=89802.351562, iteration=1, tol=0.000100]
[running kmeans]: 1it [00:08,  8.33s/it, center_shift=89802.351562, iteration=1, tol=0.000100]
[running kmeans]: 1it [00:17,  8.33s/it, center_shift=6212.250977, iteration=2, tol=0.000100] 
[running kmeans]: 2it [00:17,  9.08s/it, center_shift=6212.250977, iteration=2, tol=0.000100]
[running kmeans]: 2it [00:30,  9.08s/it, center_shift=2467.134033, iteration=3, tol=0.000100]
[running kmeans]: 3it [00:30, 10.69s/it, center_shift=2467.134033, iteration=3, tol=0.000100]
[running kmeans]: 3it [00:34, 10.69s/it, center_shift=1020.569641, iteration=4, tol=0.000100]
[running kmeans]: 4it [00:34,  7.96s/it, center_shift=1020.569641, iteration=4, tol=0.000100]
[running kmeans]: 4it [00:37,  7.96s/it, center_shift=534.985046, iteration=5, tol=0.000100] 
[running kmeans]: 5it [00:38,  6.42s/it, center_shift=534.985046, iteration=5, tol=0.000100]
[running kmeans]: 5it [0


230.3351697921753


In [17]:
print(cluster_ids_x)
print(cluster_centers)

tensor([17, 78, 78,  ...,  2, 20,  1])
tensor([[ 0.0812,  0.1334, -0.1107,  ..., -0.0461,  0.0361,  0.1923],
        [ 0.0314,  0.1396,  0.0531,  ..., -0.0448,  0.0161,  0.1095],
        [ 0.0550,  0.1556,  0.0045,  ..., -0.0610, -0.1153,  0.0474],
        ...,
        [-0.0973,  0.1178, -0.0665,  ...,  0.0960,  0.0286,  0.2469],
        [ 0.0191,  0.1475, -0.2121,  ...,  0.1577, -0.1047, -0.1347],
        [-0.0308,  0.2546,  0.0544,  ..., -0.0603, -0.1300, -0.0379]])


In [18]:
len(set(cluster_ids_x))

30000

In [19]:
device

device(type='cpu')

In [20]:
!nvidia-smi

Fri Aug 19 12:49:55 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   47C    P0    27W /  70W |    906MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
# print(cluster_ids_x)
# print(cluster_centers)

In [ ]:
# cluster_centers

In [17]:
# begin = time.time()

# cluster_ids_x, cluster_centers = kmeans(
#     X=b2,
#     num_clusters=num_clusters,
#     cluster_centers = cluster_centers,
#     distance='cosine',
#     device=device,
# )

# print()
# print(time.time() - begin)

running k-means on cpu..
resuming


[running kmeans]: 38it [00:57,  1.53s/it, center_shift=0.000000, iteration=38, tol=0.000100]


59.47051739692688


In [18]:
# begin = time.time()

# cluster_ids_x, cluster_centers = kmeans(
#     X=b3,
#     cluster_centers = cluster_centers,
#     num_clusters=num_clusters,
#     distance='cosine',
#     device=device
# )

# print()
# print(time.time() - begin)

running k-means on cpu..
resuming


[running kmeans]: 33it [00:49,  1.51s/it, center_shift=0.000000, iteration=33, tol=0.000100]


51.37775921821594


In [19]:
# print(cluster_ids_x)
# print(cluster_centers)

In [20]:
begin = time.time()

cluster_ids_x, cluster_centers = kmeans(
    X=b4,
    num_clusters=num_clusters,
    distance='cosine',
    cluster_centers = cluster_centers,
    device=device
)

print()
print(time.time() - begin)

running k-means on cpu..
resuming


[running kmeans]: 27it [00:23,  1.15it/s, center_shift=0.000000, iteration=27, tol=0.000100]


24.38821244239807


In [18]:
# print(cluster_ids_x)
# print(cluster_centers)

In [ ]:
cluster_ids_X = kmeans_predict(
    X=X[:32000],
    cluster_centers = cluster_centers,
    distance='cosine',
    device=device,
)

predicting on cpu..


In [34]:
cluster_ids_X

tensor([ 50, 134, 134,  ...,  50, 124,  53])

In [35]:
len(set(cluster_ids_X))

30000

In [ ]:
cluster_centers.shape

In [ ]:
from nltk.cluster import KMeansClusterer, cosine_distance
import numpy as np

In [ ]:
# vectors = [np.array(f) for f in [[2, 1], [1, 3], [4, 7], [6, 7]]]
# # means = [[4, 3], [5, 5]]

In [ ]:
X.shape

(35667, 1280)

In [ ]:
v = X[0:23000, :]

In [ ]:
v.shape

(23000, 1280)

In [ ]:
# K=5

In [ ]:
K=153

begin = time.time()

clusterer = KMeansClusterer(num_means=K, 
                            distance=cosine_distance,
                            initial_means=None,
                            repeats=1)
clusters = clusterer.cluster(v, True, trace=True)

# print("Clustered:", vectors)
print("As:", clusters)
print("Means:", clusterer.means())
print()

print(f'Time elapsed: {time.time() - begin} seconds')

k-means trial 0
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
iteration
As: [26, 16, 16, 26, 26, 16, 26, 26, 16, 148, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 38, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16

In [ ]:
# help(KMeansClusterer)

In [ ]:
len(clusters)

23000