### -1. Required Packages

In [6]:
import esm
import torch
import numpy as np # Saved file(s) in .npy format.

### O. Testing: Dataset Prepossessing & Generation

In [7]:
# !python scripts/extract.py esm1b_t33_650M_UR50S examples/data/some_proteins.fasta examples/data/some_proteins_emb_esm1b/ --repr_layers 0 32 33 --include mean per_tok

In [8]:
# FASTA_PATH = '/home/rafsanjani/backup-research/esm/examples/data/some_proteins.fasta'
# EMB_PATH = '/home/rafsanjani/backup-research/esm/examples/data/some_proteins_emb_esm1b'
# EMB_LAYER = 33

In [9]:
# Xs = []
# for header, _seq in esm.data.read_fasta(FASTA_PATH):
#     fn = f'{EMB_PATH}/{header[1:]}.pt'
#     embs = torch.load(fn)
#     Xs.append(embs['mean_representations'][EMB_LAYER])
# Xs = torch.stack(Xs, dim=0).numpy()
# print(Xs.shape)

In [10]:
# type(Xs[0])

In [11]:
# !python scripts/extract.py esm1b_t33_650M_UR50S examples/data/some_proteins_evil.fasta examples/data/some_proteins_evil_emb_esm1b/ --repr_layers 0 32 33 --include mean per_tok

In [12]:
# FASTA_PATH = '/home/rafsanjani/backup-research/esm/examples/data/some_proteins_evil.fasta'
# EMB_PATH = '/home/rafsanjani/backup-research/esm/examples/data/some_proteins_evil_emb_esm1b'
# EMB_LAYER = 33

In [13]:
# Xs = []
# for header, _seq in esm.data.read_fasta(FASTA_PATH):
#     fn = f'{EMB_PATH}/{header[1:]}.pt'
#     embs = torch.load(fn)
#     # print(embs)
#     # print()
#     Xs.append(embs['mean_representations'][EMB_LAYER])
# Xs = torch.stack(Xs, dim=0).numpy()
# print(Xs.shape)

In [14]:
# Xs = []
# for header, _seq in esm.data.read_fasta(FASTA_PATH):
#     # fn = f'{EMB_PATH}/{header[1:]}.pt'
#     print(header[1:])
    

In [15]:
# Xs.shape

In [16]:
# Xs.shape

In [17]:
 # !python scripts/extract.py esm1b_t33_650M_UR50S examples/data/astral_seg.fa examples/data/astral_esm1b/ --repr_layers 0 32 33 --include mean per_tok

### 1. Download FASTA Sequences from SCOPe Database:

In [13]:
!wget 'https://scop.berkeley.edu/downloads/scopeseq-2.08/astral-scopedom-seqres-sel-gs-bib-95-2.08.fa'

--2022-08-15 22:24:12--  https://scop.berkeley.edu/downloads/scopeseq-2.08/astral-scopedom-seqres-sel-gs-bib-95-2.08.fa
Resolving scop.berkeley.edu (scop.berkeley.edu)... 128.32.236.13
Connecting to scop.berkeley.edu (scop.berkeley.edu)|128.32.236.13|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9862103 (9.4M)
Saving to: ‘astral-scopedom-seqres-sel-gs-bib-95-2.08.fa’

astral-scopedom-seq 100%[===================>]   9.40M   576KB/s    in 17s     

2022-08-15 22:24:31 (559 KB/s) - ‘astral-scopedom-seqres-sel-gs-bib-95-2.08.fa’ saved [9862103/9862103]



In [14]:
!mv astral-scopedom-seqres-sel-gs-bib-95-2.08.fa astral-SCOPe-original.fa

In [15]:
!ls

astral95+15.fa		   astral-SCOPe+original.fa	 pyproject.toml
astral95-15.fa		   astral-SCOPe-original.fa	 README.md
astral95+ESM1b+15	   astral-SCOPe+refined+1024.fa  scripts
astral95+ESM1b-15	   astral-SCOPe+refined.fa	 scrutinize.ipynb
astral95_ESM1b_refined	   CODE_OF_CONDUCT.rst		 setup.py
astral95+original.fa	   CONTRIBUTING.md		 tests
astral95_refined_2500.fa   countCrash.txt		 trackError.ipynb
astral95_refined_2500.txt  esm				 Xs-2500.npy
astral95+refined.fa	   esm-embedding.ipynb		 Xs-35652.npy
astral-common.fa	   examples			 Xs.npy
astral-glr.fa		   hubconf.py
astral-SCOPe-ESM1b	   LICENSE


### 2. Trim Sequences (maximum length is 1024)

In [18]:
C = 1
file = open('astral-SCOPe-refined.fa', 'w')
for header, sequence in esm.data.read_fasta('astral-SCOPe-original.fa'):
    headerSegment1 = header.split()[0]
    headerSegment2 = '.'.join(header.split()[1].split('.')[0:-1])
    
    header = ''.join([headerSegment1, headerSegment2])
    sequence = sequence.upper()[:1022] 
    # ESM tool able to handle maximum 1024-sequence length
    # We merely can generate data with 1022-sequence length (i.e., a starting pointer and an ending pointer are required.).
    
    # print(header)
    # print(sequence)
    
    file.write(f'{header}\n')
    file.write(f'{sequence}\n')
    
    # print()
    # if C==11: break
    # C += 1
#end-for
file.close()

In [36]:
# help(file.write)

In [37]:
# ''.join(['A', '+B'])

### Sequences to .pt formats (required 100GB Space, massive computation)

- It utilizes __ESM-1b__ (esm1b_t33_650M_UR50S) as pre-trained model to generate __.pt files__ for each sequence.

In [ ]:
 !python scripts/extract.py esm1b_t33_650M_UR50S astral-SCOPe-refined.fa astral-SCOPe-ESM1b/ --repr_layers 0 32 33 --include mean per_tok

Read astral-SCOPe-refined.fa with 35667 sequences
Processing 1 of 1635 batches (141 sequences)


- It has been deliberately inturrupted.

In [19]:
 # !python scripts/extract.py esm1b_t33_650M_UR50S trackError.fa astral95+ESM1b+15/ --repr_layers 0 32 33 --include mean per_tok

In [20]:
 # !python scripts/extract.py esm1b_t33_650M_UR50S astral95_refined.fa astral95_ESM1b --repr_layers 0 32 33 --include mean per_tok

In [21]:
# datasetLocation = '/home/rafsanjani/backup-research/esm/astral95_refined.fa'
# embeddingLocation = '/home/rafsanjani/backup-research/esm/astral95_ESM1b'
# embeddingLayer = 33

# # astral95_refined_2500.txt astral95_ESM1b_refined

In [22]:
datasetLocation = '/home/rafsanjani/backup-research/esm/astral-SCOPe-refined.fa'
embeddingLocation = '/home/rafsanjani/backup-research/esm/astral-SCOPe-ESM1b'
embeddingLayer = 33

In [23]:
Xs = []
for header, _seq in esm.data.read_fasta(datasetLocation):
    fn = f'{embeddingLocation}/{header[1:]}.pt'
    embedding = torch.load(fn)
    # print(embs)
    # print()
    Xs.append(embedding['mean_representations'][embeddingLayer])
#end-for
Xs = torch.stack(Xs, dim=0).numpy()
print(Xs.shape)

(35667, 1280)


In [24]:
np.save(arr=Xs, file='Xs-35667')

In [25]:
v = np.load('Xs-35667.npy')

In [26]:
v.shape

(35667, 1280)

In [27]:
v[0].shape

(1280,)

In [28]:
C = 1
for header, _seq in esm.data.read_fasta(datasetLocation):
    # fn = f'{EMB_PATH}/{header[1:]}.pt'
    print(header)
    
    if C==20: break
    C+=1

>d1ux8a_a.1.1
>d1dlwa_a.1.1
>d1dlya_a.1.1
>d2gkma_a.1.1
>d1ngka_a.1.1
>d1s69a_a.1.1
>d5v3ta_a.1.1
>d2bkma_a.1.1
>d4i0va_a.1.1
>d2bmma_a.1.1
>d1asha_a.1.1
>d1vhba_a.1.1
>d1ch4a_a.1.1
>d2dc3a_a.1.1
>d2dc3b_a.1.1
>d1ut0a_a.1.1
>d4hswa_a.1.1
>d1ecaa_a.1.1
>d1x9fd_a.1.1
>d1x9fb_a.1.1


In [29]:
# C=1
# SUM = 0
# with open(file='countCrash.txt', mode='r') as file:
#     for i in file:
#         v = int(i.split()[-2][1:])
#         SUM += v
#         # if C==10: break
#         # C+=1
#     print(SUM)
    

In [30]:
# 'ra fa'.split()

In [32]:
# v = 'PRIKTRRSKPAPDGFEKIKPTLTDFEIQLRDAQKDKSSKLAAKSNEQLWEIMQLHHQRSRYIYTLYYKRKAISKDLYDWLIKEKYADKLLIAKWRKTGYEKLCCLRCIQKNETNNGSTCICRVPRAQLEEEARKKGTQVSFHQCVHCGCRGCASTD'

In [33]:
v[0]

array([ 0.10049941,  0.03679613, -0.03360916, ...,  0.03035077,
       -0.10252801,  0.09472331], dtype=float32)

In [34]:
v[1]

array([ 0.05662494,  0.0203409 ,  0.08400498, ...,  0.07114115,
       -0.13347617,  0.21751517], dtype=float32)

In [35]:
v[2]

array([ 0.0256628 ,  0.01615633,  0.05776972, ...,  0.04173521,
       -0.05989721,  0.13533191], dtype=float32)

In [36]:
v[3]

array([ 0.00166722, -0.0244148 ,  0.0186756 , ...,  0.0658393 ,
       -0.0096192 ,  0.13409004], dtype=float32)

In [37]:
v[4]

array([ 0.10878856,  0.01696545,  0.0749026 , ...,  0.01413552,
       -0.12708436,  0.04421176], dtype=float32)